/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface A {
  name: string
}

export declare function cli(args: Array<string>): Promise<A>

export declare function plus100(input: number): number

export declare function prompt(): Promise<void>
