/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function hello(name?: string | undefined | null, input?: number | undefined | null): string

export declare function plus100(input: number): number
